// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpMnQ6OqdxqQhvzlkTkNpQTK-8pXxb97Y',
    appId: '1:978923627962:web:84a8fe9642c185ddc2a983',
    messagingSenderId: '978923627962',
    projectId: 'elever-29a7a',
    authDomain: 'elever-29a7a.firebaseapp.com',
    storageBucket: 'elever-29a7a.appspot.com',
    measurementId: 'G-6ZELKLQ2NX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlGnRscLclZGGSwhZUWpRIys7oT-K_yjQ',
    appId: '1:978923627962:android:384b50a12364b924c2a983',
    messagingSenderId: '978923627962',
    projectId: 'elever-29a7a',
    storageBucket: 'elever-29a7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCMGyWwYImgONAbC1C75yA3-GRzGvgWFk',
    appId: '1:978923627962:ios:27aba194ae8622d7c2a983',
    messagingSenderId: '978923627962',
    projectId: 'elever-29a7a',
    storageBucket: 'elever-29a7a.appspot.com',
    iosClientId: '978923627962-bcuak28l0duu72n7r4i0t33tinnhjqph.apps.googleusercontent.com',
    iosBundleId: 'com.example.eleverdev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCMGyWwYImgONAbC1C75yA3-GRzGvgWFk',
    appId: '1:978923627962:ios:27aba194ae8622d7c2a983',
    messagingSenderId: '978923627962',
    projectId: 'elever-29a7a',
    storageBucket: 'elever-29a7a.appspot.com',
    iosClientId: '978923627962-bcuak28l0duu72n7r4i0t33tinnhjqph.apps.googleusercontent.com',
    iosBundleId: 'com.example.eleverdev',
  );
}
